export const deck = [
  {
    name: "Strike4",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 4,
    player: "your",
  },
  {
    name: "Strike5",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 5,
    player: "your",
  },
  {
    name: "Strike6",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 6,
    player: "your",
  },
  {
    name: "Strike7",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 7,
    player: "your",
  },
  {
    name: "Strike8",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 8,
    player: "your",
  },
  {
    name: "Defense1",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 9,
    player: "your",
  },
  {
    name: "Defense7",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 15,
    player: "your",
  },
  {
    name: "Defense8",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 16,
    player: "your",
  },
  {
    name: "Defense2",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 10,
    player: "your",
  },
  {
    name: "Strike1",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 1,
    player: "your",
  },
  {
    name: "Strike2",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 2,
    player: "your",
  },
  {
    name: "Strike3",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: 6,
    defense: 0,
    mana: 1,
    id: 3,
    player: "your",
  },
  {
    name: "Defense3",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 11,
    player: "your",
  },
  {
    name: "Defense4",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 12,
    player: "your",
  },
  {
    name: "Defense5",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 13,
    player: "your",
  },
  {
    name: "Defense6",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 14,
    player: "your",
  },
];

export const deck2 = [
  {
    name: "This enemy intends to Attack for 0-4 damage",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * 4),
    defense: 0,
    mana: 1,
    id: 1,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 0-4 damage",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * 4),
    defense: 0,
    mana: 1,
    id: 1,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 5-9 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (9 - 5) + 5),
    defense: 0,
    mana: 1,
    id: 2,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 5-9 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (9 - 5) + 5),
    defense: 0,
    mana: 1,
    id: 2,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 5-9 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (9 - 5) + 5),
    defense: 0,
    mana: 1,
    id: 2,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 10-14 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (14 - 10) + 10),
    defense: 0,
    mana: 1,
    id: 3,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 10-14 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (14 - 10) + 10),
    defense: 0,
    mana: 1,
    id: 3,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 15-19 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (19 - 15) + 15),
    defense: 0,
    mana: 1,
    id: 4,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 15-19 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (19 - 15) + 15),
    defense: 0,
    mana: 1,
    id: 4,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 20-24 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (24 - 20) + 20),
    defense: 0,
    mana: 1,
    id: 5,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 25-29 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (29 - 25) + 25),
    defense: 0,
    mana: 1,
    id: 6,
    player: "foes",
  },
  {
    name: "This enemy intends to Attack for 30-50 damage.",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (50 - 30) + 30),
    defense: 0,
    mana: 1,
    id: 7,
    player: "foes",
  },
  {
    name: "This enemy intends to attack for 0-4 and inflict a Negative Effect on you. ",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * 4),
    defense: 0,
    mana: 1,
    id: 8,
    player: "foes",
  },
  {
    name: "This enemy intends to attack for 10-14 and inflict a Negative Effect on you. ",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (14 - 10) + 10),
    defense: 0,
    mana: 1,
    id: 8,
    player: "foes",
  },
  {
    name: "This enemy intends to attack for 15-19 and inflict a Negative Effect on you. ",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (15 - 19) + 19),
    defense: 0,
    mana: 1,
    id: 8,
    player: "foes",
  },
  {
    name: "This enemy intends to attack for 20-24 and inflict a Negative Effect on you. ",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (24 - 20) + 20),
    defense: 0,
    mana: 1,
    id: 8,
    player: "foes",
  },
  {
    name: "This enemy intends to attack for 25-29 and inflict a Negative Effect on you. ",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Sword_Pixel_art_-_Radin.png",
    attack: Math.ceil(Math.random() * (29 - 25) + 25),
    defense: 0,
    mana: 1,
    id: 8,
    player: "foes",
  },
  {
    name: "This enemy intends to block Block",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: Math.ceil(Math.random() * (20 - 6) + 6),
    mana: 1,
    id: 9,
    player: "foes",
  },
  {
    name: "This enemy intends to inflict a Negative Effect on you.",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 10,
    player: "foes",
  },
  {
    name: "This enemy intends to inflict a powerful Negative Effect on you.",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 11,
    player: "foes",
  },
  {
    name: "This enemy intends to use a Buff.",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: 5,
    mana: 1,
    id: 12,
    player: "foes",
  },
  {
    name: "This enemy intends to block Block and use inflict a Negative Effect on you.",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: Math.ceil(Math.random() * (20 - 6) + 6),
    mana: 1,
    id: 13,
    player: "foes",
  },
  {
    name: "This enemy intends to block Block and use inflict a Negative Effect on you.",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: Math.ceil(Math.random() * (20 - 6) + 6),
    mana: 1,
    id: 13,
    player: "foes",
  },
  {
    name: "This enemy intends to block Block and use a Buff.",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 0,
    defense: Math.ceil(Math.random() * (20 - 6) + 6),
    mana: 1,
    id: 14,
    player: "foes",
  },
].sort(() => Math.random() - 0.5);

const newCards = [
  {
    name: "Bash1",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 8,
    defense: 0,
    debuff: {
      type: "VULNERABLE",
      turns: 2,
    },
    mana: 2,
    id: 17,
    player: "your",
  },
  {
    name: "Bash2",
    img: "http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/e988f5dbfac3240.png",
    attack: 8,
    defense: 0,
    debuff: {
      type: "VULNERABLE",
      turns: 2,
    },
    mana: 2,
    id: 18,
    player: "your",
  },
];
